modLoader="javafml"
loaderVersion="[43,)"
license="GPL-3.0 license"


[[mods]]
modId="halloween_mood"
version="${file.jarVersion}"
displayName="Halloween Mood"
logoFile="halloween_mood.png"
credits="noeppi-noeppi, Kaunpenjoe for his videos"
authors="TATHAN"
description='''
This mod adds a Halloween/Autumn mood to Minecraft !
If you are brave enough, you can turn the halloween difficulty on...
'''

[[dependencies.halloween_mood]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.halloween_mood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"